import type { Metadata } from "next";
import { montserrat } from "@/app/ui/font";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material";
import AppHeader from "@/app/ui/header";
import "./globals.css";
import { theme } from "./ui/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <AppRouterCacheProvider>
          <AppHeader />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
